import { expect, test, type Browser } from "@playwright/test";
import { entry, hostCall, manualFragment, playerCall, surfaceCallArg, waitForSurface } from "./lib";

test("GM authors a real tile and graph in the wizard, then activates it by clicking the map", async ({ page }) => {
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  const tile = zones.locator("[data-zone-tile-create]");
  await tile.getByLabel("Tile name").fill("Bell tile");
  await tile.getByLabel("X", { exact: true }).fill("350");
  await tile.getByLabel("Y", { exact: true }).fill("400");
  await tile.getByLabel("Width").fill("200");
  await tile.getByLabel("Height").fill("160");
  await tile.locator("[data-zone-create-tile]").click();
  await expect(zones.locator("[data-zone-tile] option").filter({ hasText: "Bell tile" })).toHaveCount(1);
  await zones.locator("[data-zone-name]").fill("Bell trap");
  await zones.locator(".methods label").filter({ hasText: "click" }).locator("input").check();
  await zones.locator("[data-zone-save]").click();
  await expect(zones.locator("li").filter({ hasText: "Bell trap" })).toHaveCount(1);
  await page.locator('[data-window="macros"] [data-window-close]').click();
  await page.locator('[data-canvas-layer="map"]').click();
  const before = await hostCall<number>(page, "seq");
  const point = await page.evaluate(() => {
    const stage = (globalThis as unknown as { __stage?: {
      app: { canvas: HTMLCanvasElement }; camera: { x: number; y: number; scale: number };
    } }).__stage;
    if (!stage) throw new Error("GM canvas missing");
    const rect = stage.app.canvas.getBoundingClientRect();
    return { x: rect.left + (450 - stage.camera.x) * stage.camera.scale,
      y: rect.top + (480 - stage.camera.y) * stage.camera.scale };
  });
  await page.mouse.click(point.x, point.y);
  await expect.poll(() => hostCall<number>(page, "seq")).toBeGreaterThan(before);
  await expect(page.locator("#chat-log")).toContainText("click by");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const history = page.locator("[data-zone-history]");
  await history.locator("summary").click();
  await expect(history.locator("li")).toContainText("click · gm");
  await page.locator("[data-zone-reset-history]").click();
  await expect(page.locator("[data-active-zones] li").filter({ hasText: "Bell trap" })).toContainText("0 run(s)");
  await expect(page.locator("[data-zone-history]")).toHaveCount(0);
});

test("wizard filters the current collection by a typed attribute before a count check, using the live host tile", async ({ page }) => {
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  const tile = zones.locator("[data-zone-tile-create]");
  await tile.getByLabel("Tile name").fill("Attribute tile");
  await tile.getByLabel("Width").fill("200");
  await tile.locator("[data-zone-create-tile]").click();
  await expect(zones.locator("[data-zone-tile] option").filter({ hasText: "Attribute tile" })).toHaveCount(1);
  await zones.locator("[data-zone-name]").fill("Typed width filter");
  await zones.locator('[data-zone-step="select"]').getByLabel("Current collection").selectOption("tile");
  await zones.getByRole("button", { name: "Remove step 2" }).click();
  await zones.locator('[data-zone-add="attributes"]').click();
  const attr = zones.locator("[data-zone-step]").last();
  await attr.getByLabel("Attribute path").fill("width");
  await attr.getByLabel("Attribute comparison").selectOption("gte");
  await expect(attr.getByLabel("Attribute value type")).toHaveValue("number");
  await attr.getByLabel("Attribute value", { exact: true }).fill("200");
  await zones.locator('[data-zone-add="filter"]').click();
  await zones.locator('[data-zone-add="chat"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Text").fill("Width matches");
  await zones.locator("[data-zone-save]").click();
  await expect(zones.locator("li").filter({ hasText: "Typed width filter" })).toHaveCount(1);
  await expect(zones.getByRole("alert")).toHaveCount(0);
  const before = await hostCall<number>(page, "seq");
  await zones.locator("[data-zone-run]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 1);
  await expect(page.locator("#chat-log")).toContainText("Width matches");
  await expect(zones.locator("details[open] li").filter({ hasText: "attribute filter: 1 matching" })).toHaveCount(1);
  await zones.locator("[data-zone-step]").nth(1).getByLabel("Attribute value", { exact: true }).fill("250");
  await zones.locator("[data-zone-save]").click();
  const afterEdit = await hostCall<number>(page, "seq");
  await zones.locator("[data-zone-run]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(afterEdit + 1);
  await expect(zones.locator("details[open] li").filter({ hasText: "attribute filter: 0 matching" })).toHaveCount(1);
  await expect(page.locator("#chat-log").getByText("Width matches")).toHaveCount(1);
  await expect(zones.locator("li").filter({ hasText: "Typed width filter" })).toContainText("2 run(s)");
});

test("Check Data wizard checks the triggering tile instead of the empty token collection", async ({ page }) => {
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  await zones.locator("[data-zone-tile-create]").getByLabel("Tile name").fill("Data tile");
  await zones.locator("[data-zone-create-tile]").click();
  await zones.locator("[data-zone-name]").fill("Tile width check");
  await zones.getByRole("button", { name: "Remove step 2" }).click();
  await zones.locator('[data-zone-add="checkData"]').click();
  const check = zones.locator("[data-zone-step]").nth(1);
  await check.getByLabel("Check Data tile path").fill("width");
  await check.getByLabel("Attribute comparison").selectOption("gte");
  await check.getByLabel("Attribute value type").selectOption("number");
  await check.getByLabel("Attribute value", { exact: true }).fill("200");
  await check.getByLabel("Check Data failure landing").fill("too-small");
  await zones.locator('[data-zone-add="chat"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Text").fill("The tile is wide");
  await zones.locator('[data-zone-add="stop"]').click();
  await zones.locator('[data-zone-add="landing"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Landing name").fill("too-small");
  await zones.locator('[data-zone-add="chat"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Text").fill("The tile is narrow");
  await zones.locator("[data-zone-save]").click();
  await expect(zones.getByRole("alert")).toHaveCount(0);
  await zones.getByLabel("Simulate method").selectOption("manual");
  const before = await hostCall<number>(page, "seq");
  await zones.locator("[data-zone-run]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 1);
  await expect(page.locator("#chat-log").getByText("The tile is wide")).toHaveCount(1);
  await expect(zones.locator("details[open] li").filter({ hasText: "Check Data width: pass" })).toHaveCount(1);
  await check.getByLabel("Attribute value", { exact: true }).fill("250");
  await zones.locator("[data-zone-save]").click();
  const afterEdit = await hostCall<number>(page, "seq");
  await zones.locator("[data-zone-run]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(afterEdit + 1);
  await expect(page.locator("#chat-log").getByText("The tile is narrow")).toHaveCount(1);
  await expect(zones.locator("details[open] li").filter({ hasText: "Check Data width: fail" })).toHaveCount(1);
});

test("Token Trigger Count wizard branches separately for two real tokens, with undoable private history", async ({ page }) => {
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  await page.locator("#add-token").click();
  await page.locator("#add-token").click();
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  await zones.locator("[data-zone-tile-create]").getByLabel("Tile name").fill("Token history tile");
  await zones.locator("[data-zone-create-tile]").click();
  await zones.locator("[data-zone-name]").fill("Per-token first fire");
  await zones.getByRole("button", { name: "Remove step 2" }).click();
  await zones.locator('[data-zone-add="tokenTriggerCount"]').click();
  const count = zones.locator("[data-zone-step]").nth(1);
  await count.getByLabel("Token trigger count comparison").selectOption("eq");
  await count.getByLabel("Token trigger count", { exact: true }).fill("1");
  await zones.locator('[data-zone-add="filter"]').click();
  await zones.locator("[data-zone-step]").nth(2).getByLabel("On failure jump to").fill("repeat");
  await zones.locator('[data-zone-add="chat"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Text").fill("first per token");
  await zones.locator('[data-zone-add="stop"]').click();
  await zones.locator('[data-zone-add="landing"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Landing name").fill("repeat");
  await zones.locator('[data-zone-add="chat"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Text").fill("already fired");
  await zones.locator("[data-zone-save]").click();
  await expect(zones.getByRole("alert")).toHaveCount(0);
  await zones.getByLabel("Simulate method").selectOption("manual");
  await zones.getByLabel("Origin token").selectOption({ label: "Token 1" });
  await zones.locator("[data-zone-run]").click();
  await expect(page.locator("#chat-log").getByText("first per token")).toHaveCount(1);
  await expect(zones.locator("details[open] li").filter({ hasText: "token trigger count filter: 1 matching" })).toHaveCount(1);
  await zones.locator("[data-zone-run]").click();
  await expect(page.locator("#chat-log").getByText("already fired")).toHaveCount(1);
  await zones.getByLabel("Origin token").selectOption({ label: "Token 2" });
  await zones.locator("[data-zone-run]").click();
  await expect(page.locator("#chat-log").getByText("first per token")).toHaveCount(2);
  await page.getByRole("button", { name: /Undo \(Ctrl\+Z\)/ }).click();
  await expect(page.locator("#chat-log").getByText("first per token")).toHaveCount(1);
  await zones.locator("[data-zone-run]").click();
  await expect(page.locator("#chat-log").getByText("first per token")).toHaveCount(2);
});

test("Check Variable wizard branches on a staged tile value, persists, and undo restores the prior value", async ({ page }) => {
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  await zones.locator("[data-zone-tile-create]").getByLabel("Tile name").fill("Counter tile");
  await zones.locator("[data-zone-create-tile]").click();
  await expect(zones.locator("[data-zone-tile] option").filter({ hasText: "Counter tile" })).toHaveCount(1);
  await zones.locator("[data-zone-name]").fill("Charge check");
  await zones.getByRole("button", { name: "Remove step 2" }).click();
  await zones.locator('[data-zone-add="set"]').click();
  const set = zones.locator("[data-zone-step]").nth(1);
  await set.getByLabel("Name", { exact: true }).fill("charge");
  await set.getByLabel("Variable scope").selectOption("tile");
  await set.getByLabel("Variable operation").selectOption("add");
  await zones.locator('[data-zone-add="checkVariable"]').click();
  const check = zones.locator("[data-zone-step]").nth(2);
  await check.getByLabel("Variable name").fill("charge");
  await check.getByLabel("Check Variable comparison").selectOption("gte");
  await check.getByLabel("Check Variable value", { exact: true }).fill("2");
  await check.getByLabel("Check Variable failure landing").fill("early");
  await zones.locator('[data-zone-add="chat"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Text").fill("Charge ready");
  await zones.locator('[data-zone-add="stop"]').click();
  await zones.locator('[data-zone-add="landing"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Landing name").fill("early");
  await zones.locator('[data-zone-add="chat"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Text").fill("Charge pending");
  await zones.locator("[data-zone-save]").click();
  await expect(zones.getByRole("alert")).toHaveCount(0);
  await expect(zones.locator("li").filter({ hasText: "Charge check" })).toHaveCount(1);
  await zones.getByLabel("Simulate method").selectOption("manual");
  const before = await hostCall<number>(page, "seq");
  await zones.locator("[data-zone-run]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 1);
  await expect(page.locator("#chat-log").getByText("Charge pending")).toHaveCount(1);
  await expect(zones.locator("details[open] li").filter({ hasText: "Check Variable charge: 0/1" })).toHaveCount(1);
  await zones.locator("[data-zone-run]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 2);
  await expect(page.locator("#chat-log").getByText("Charge ready")).toHaveCount(1);
  await expect(zones.locator("details[open] li").filter({ hasText: "Check Variable charge: 1/1" })).toHaveCount(1);
  await page.getByRole("button", { name: /Undo \(Ctrl\+Z\)/ }).click();
  await expect(page.locator("#chat-log").getByText("Charge ready")).toHaveCount(0);
  await zones.locator("li").filter({ hasText: "Charge check" }).getByRole("button", { name: "Edit" }).click();
  await zones.locator("[data-zone-variables] summary").click();
  await expect(zones.locator("[data-zone-variables] li")).toContainText("charge: 1");
  await hostCall<number>(page, "drainOps");
  await page.reload();
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const restored = page.locator("[data-active-zones]");
  await restored.locator("li").filter({ hasText: "Charge check" }).getByRole("button", { name: "Edit" }).click();
  await restored.locator("[data-zone-variables] summary").click();
  await expect(restored.locator("[data-zone-variables] li")).toContainText("charge: 1");
  await expect(page.locator("#chat-log").getByText("Charge pending")).toHaveCount(1);
});

test("Random Number wizard rolls a bounded host value and interpolates it into real chat", async ({ page }) => {
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  await zones.locator("[data-zone-tile-create]").getByLabel("Tile name").fill("Dice tile");
  await zones.locator("[data-zone-create-tile]").click();
  await zones.locator("[data-zone-name]").fill("Die roll");
  await zones.getByRole("button", { name: "Remove step 2" }).click();
  await zones.locator('[data-zone-add="random"]').click();
  const roll = zones.locator("[data-zone-step]").nth(1);
  await roll.getByLabel("Variable").fill("die");
  await roll.getByLabel("Minimum").fill("1");
  await roll.getByLabel("Maximum").fill("6");
  await zones.locator('[data-zone-add="chat"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Text").fill("Rolled {{die}}");
  await zones.locator("[data-zone-save]").click();
  await expect(zones.getByRole("alert")).toHaveCount(0);
  await zones.getByLabel("Simulate method").selectOption("manual");
  const before = await hostCall<number>(page, "seq");
  for (let i = 1; i <= 3; i++) {
    await zones.locator("[data-zone-run]").click();
    await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + i);
  }
  const results = await page.locator("#chat-log").getByText(/^Rolled [1-6]$/).allTextContents();
  expect(results).toHaveLength(3);
  await expect(zones.locator("li").filter({ hasText: "Die roll" })).toContainText("3 run(s)");
  await expect(zones.locator("details[open] li").filter({ hasText: /die = [1-6] \(host roll\)/ })).toHaveCount(1);
});

test("Check Value wizard reads committed scene darkness and routes to an alternate landing", async ({ page }) => {
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  await zones.locator("[data-zone-tile-create]").getByLabel("Tile name").fill("Night watch tile");
  await zones.locator("[data-zone-create-tile]").click();
  await zones.locator("[data-zone-name]").fill("Night watch");
  await zones.getByRole("button", { name: "Remove step 2" }).click();
  await zones.locator('[data-zone-add="checkValue"]').click();
  const check = zones.locator("[data-zone-step]").nth(1);
  await expect(check.getByLabel("Check Value source")).toHaveValue("darkness");
  await check.getByLabel("Check Value threshold").fill("0.5");
  await check.getByLabel("Check Value failure landing").fill("daylight");
  await zones.locator('[data-zone-add="chat"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Text").fill("The shadows answer");
  await zones.locator('[data-zone-add="stop"]').click();
  await zones.locator('[data-zone-add="landing"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Landing name").fill("daylight");
  await zones.locator('[data-zone-add="chat"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Text").fill("Still daylight");
  await zones.locator("[data-zone-save]").click();
  await expect(zones.getByRole("alert")).toHaveCount(0);
  await zones.getByLabel("Simulate method").selectOption("manual");
  const before = await hostCall<number>(page, "seq");
  await zones.locator("[data-zone-run]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 1);
  await expect(page.locator("#chat-log").getByText("Still daylight")).toHaveCount(1);
  await page.locator("#gm-settings").click();
  const settings = page.locator('[data-window="settings"]');
  await settings.locator("[data-scene-darkness]").focus();
  await settings.locator("[data-scene-darkness]").press("End");
  await expect(settings.locator("[data-scene-darkness-value]")).toHaveText("100%");
  await settings.locator("[data-window-close]").click();
  await zones.locator("[data-zone-run]").click();
  await expect(page.locator("#chat-log").getByText("The shadows answer")).toHaveCount(1);
  await expect(zones.locator("details[open] li").filter({ hasText: "Check Value darkness: 1 gte 0.5 -> pass" })).toHaveCount(1);
});

test("Game Time wizard stages multiple minute changes, branches on the new clock and undoes the whole fire", async ({ page }) => {
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  await zones.locator("[data-zone-tile-create]").getByLabel("Tile name").fill("Clock lever tile");
  await zones.locator("[data-zone-create-tile]").click();
  await zones.locator("[data-zone-name]").fill("Clock lever");
  await zones.getByRole("button", { name: "Remove step 2" }).click();
  await zones.locator('[data-zone-add="gameTime"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Game Time minutes").fill("90");
  await zones.locator('[data-zone-add="checkValue"]').click();
  const first = zones.locator("[data-zone-step]").last();
  await first.getByLabel("Check Value source").selectOption("time");
  await first.getByLabel("Check Value world time").fill("01:30");
  await zones.locator('[data-zone-add="gameTime"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Game Time minutes").fill("-30");
  await zones.locator('[data-zone-add="checkValue"]').click();
  const second = zones.locator("[data-zone-step]").last();
  await second.getByLabel("Check Value source").selectOption("time");
  await second.getByLabel("Check Value comparison").selectOption("eq");
  await second.getByLabel("Check Value world time").fill("01:00");
  await zones.locator('[data-zone-add="chat"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Text").fill("Lever advanced the world clock");
  await zones.locator("[data-zone-save]").click();
  await expect(zones.getByRole("alert")).toHaveCount(0);
  await zones.getByLabel("Simulate method").selectOption("manual");
  const before = await hostCall<number>(page, "seq");
  await zones.locator("[data-zone-run]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 1);
  await expect(page.locator("#chat-log")).toContainText("Lever advanced the world clock");
  await expect(zones.locator("details[open] li").filter({ hasText: "Check Value time: 60 eq 60 -> pass" })).toHaveCount(1);
  await page.locator("#gm-settings").click();
  const settings = page.locator('[data-window="settings"]');
  await expect(settings.locator("[data-clock-readout]")).toContainText("01:00");
  await settings.locator("[data-window-close]").click();
  await page.getByRole("button", { name: /Undo \(Ctrl\+Z\)/ }).click();
  await expect(page.locator("#chat-log").getByText("Lever advanced the world clock")).toHaveCount(0);
  await page.locator("#gm-settings").click();
  await expect(settings.locator("[data-clock-readout]")).toContainText("00:00");
  await settings.locator("[data-window-close]").click();
});

test("Check Value wizard branches on the GM-replicated world clock, including day rollover", async ({ page }) => {
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  await zones.locator("[data-zone-tile-create]").getByLabel("Tile name").fill("Clock tile");
  await zones.locator("[data-zone-create-tile]").click();
  await zones.locator("[data-zone-name]").fill("After one");
  await zones.getByRole("button", { name: "Remove step 2" }).click();
  await zones.locator('[data-zone-add="checkValue"]').click();
  const check = zones.locator("[data-zone-step]").nth(1);
  await check.getByLabel("Check Value source").selectOption("time");
  await check.getByLabel("Check Value world time").fill("01:00");
  await check.getByLabel("Check Value failure landing").fill("early");
  await zones.locator('[data-zone-add="chat"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Text").fill("Clock has passed one");
  await zones.locator('[data-zone-add="stop"]').click();
  await zones.locator('[data-zone-add="landing"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Landing name").fill("early");
  await zones.locator('[data-zone-add="chat"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Text").fill("Clock has not passed one");
  await zones.locator("[data-zone-save]").click();
  await expect(zones.getByRole("alert")).toHaveCount(0);
  await zones.getByLabel("Simulate method").selectOption("manual");
  const before = await hostCall<number>(page, "seq");
  await zones.locator("[data-zone-run]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 1);
  await expect(page.locator("#chat-log").getByText("Clock has not passed one")).toHaveCount(1);
  await page.locator("#gm-settings").click();
  const settings = page.locator('[data-window="settings"]');
  await settings.locator("[data-clock-hour]").click();
  await expect(settings.locator("[data-clock-readout]")).toContainText("01:00");
  await settings.locator("[data-window-close]").click();
  await zones.locator("[data-zone-run]").click();
  await expect(page.locator("#chat-log").getByText("Clock has passed one")).toHaveCount(1);
  await expect(zones.locator("details[open] li").filter({ hasText: "Check Value time: 60 gte 60 -> pass" })).toHaveCount(1);
  await page.locator("#gm-settings").click();
  await settings.locator("[data-clock-day]").click();
  await expect(settings.locator("[data-clock-readout]")).toContainText("01:00");
  await settings.locator("[data-window-close]").click();
  await zones.locator("[data-zone-run]").click();
  await expect(page.locator("#chat-log").getByText("Clock has passed one")).toHaveCount(2);
});

test("wizard authors host condition and inventory item-count filters with a count branch", async ({ page }) => {
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  expect(await surfaceCallArg<{ ok: boolean }>(page, "app", "pf1ePlaceTokens", [
    { id: "condition-runner", col: 1, row: 1, size: "Medium" },
  ])).toMatchObject({ ok: true, placed: 1 });
  await expect.poll(() => hostCall<number>(page, "tokenCount")).toBe(1);
  expect(await surfaceCallArg<{ ok: boolean }>(page, "app", "pf1eAuthorActor", {
    actorId: "a-condition-runner", patch: { conditions: ["Prone"] },
  })).toMatchObject({ ok: true });
  await expect.poll(() => surfaceCallArg<Record<string, unknown> | null>(page, "app", "pf1eActorSystem", "a-condition-runner"))
    .toMatchObject({ conditions: ["Prone"] });
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  const tile = zones.locator("[data-zone-tile-create]");
  await tile.getByLabel("Tile name").fill("Inventory and condition tile");
  await tile.locator("[data-zone-create-tile]").click();
  await expect(zones.locator("[data-zone-tile] option").filter({ hasText: "Inventory and condition tile" })).toHaveCount(1);
  await zones.locator("[data-zone-name]").fill("Condition and item records");
  await zones.locator('[data-zone-step="select"]').getByLabel("Current collection").selectOption("inside");
  await zones.getByRole("button", { name: "Remove step 2" }).click();
  await zones.locator('[data-zone-add="condition"]').click();
  const condition = zones.locator("[data-zone-step]").nth(1);
  await condition.getByLabel("Condition or effect name").fill("  prone ");
  await condition.getByLabel("Condition mode").selectOption("has");
  await zones.locator('[data-zone-add="inventory"]').click();
  const inventory = zones.locator("[data-zone-step]").nth(2);
  await inventory.getByLabel("Inventory item name").fill("*potion*");
  await inventory.getByLabel("Inventory comparison").selectOption("eq");
  await inventory.getByLabel("Inventory item count").fill("0");
  await zones.locator('[data-zone-add="filter"]').click();
  await zones.locator('[data-zone-add="chat"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Text").fill("Condition and zero potions");
  await zones.locator("[data-zone-save]").click();
  await expect(zones.locator("li").filter({ hasText: "Condition and item records" })).toHaveCount(1);
  await expect(zones.getByRole("alert")).toHaveCount(0);
  const before = await hostCall<number>(page, "seq");
  await zones.locator("[data-zone-run]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 1);
  await expect(page.locator("#chat-log").getByText("Condition and zero potions")).toHaveCount(1);
  await expect(zones.locator("details[open] li").filter({ hasText: "condition filter: 1 matching" })).toHaveCount(1);
  await expect(zones.locator("details[open] li").filter({ hasText: "inventory filter: 1 matching" })).toHaveCount(1);

  await inventory.getByLabel("Inventory comparison").selectOption("gte");
  await inventory.getByLabel("Inventory item count").fill("1");
  await zones.locator("[data-zone-save]").click();
  const afterEdit = await hostCall<number>(page, "seq");
  await zones.locator("[data-zone-run]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(afterEdit + 1);
  await expect(zones.locator("details[open] li").filter({ hasText: "inventory filter: 0 matching" })).toHaveCount(1);
  await expect(page.locator("#chat-log").getByText("Condition and zero potions")).toHaveCount(1);
  await expect(zones.locator("li").filter({ hasText: "Condition and item records" })).toContainText("2 run(s)");
});

test("wizard publishes a bounded per-token loop with a tile-count branch and named method route", async ({ page }) => {
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  await page.locator("#add-token").click();
  await page.locator("#add-token").click();
  await expect.poll(() => hostCall<number>(page, "tokenCount")).toBe(2);
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  const tile = zones.locator("[data-zone-tile-create]");
  await tile.getByLabel("Tile name").fill("Two tokens zone");
  await tile.getByLabel("X", { exact: true }).fill("850");
  await tile.getByLabel("Y", { exact: true }).fill("600");
  await tile.getByLabel("Width").fill("300");
  await tile.getByLabel("Height").fill("300");
  await tile.locator("[data-zone-create-tile]").click();
  await expect(zones.locator("[data-zone-tile] option").filter({ hasText: "Two tokens zone" })).toHaveCount(1);
  await zones.locator("[data-zone-name]").fill("Visitors graph");
  await zones.locator(".methods label").filter({ hasText: "click" }).locator("input").check();
  await zones.locator('[data-zone-step="select"]').getByLabel("Current collection").selectOption("inside");
  await zones.getByRole("button", { name: "Remove step 2" }).click();
  await zones.locator('[data-zone-add="forEach"]').click();
  const loop = zones.locator('[data-zone-step]').nth(1);
  await loop.getByLabel(/Add inside loop/).selectOption("chat");
  await zones.locator('[data-zone-step]').nth(2).getByLabel("Text").fill("Visited {{index}}/{{currentId}}");
  await zones.locator('[data-zone-add="filter"]').click();
  const count = zones.locator('[data-zone-step]').nth(4);
  await count.getByLabel("Check").selectOption("tileCount");
  await count.getByLabel("At most").fill("1");
  await zones.locator('[data-zone-add="routeMethod"]').click();
  const route = zones.locator('[data-zone-step]').nth(5);
  await route.getByLabel("enter landing").fill("");
  await route.getByLabel("click landing").fill("clicked");
  await zones.locator('[data-zone-add="landing"]').click();
  await zones.locator('[data-zone-step]').nth(6).getByLabel("Landing name").fill("clicked");
  await zones.locator('[data-zone-add="chat"]').click();
  await zones.locator('[data-zone-step]').nth(7).getByLabel("Text").fill("Once {{count}}");
  await zones.locator("[data-zone-save]").click();
  await expect(zones.locator("li").filter({ hasText: "Visitors graph" })).toHaveCount(1);
  await page.locator('[data-window="macros"] [data-window-close]').click();
  await page.locator('[data-canvas-layer="map"]').click();
  const point = await page.evaluate(() => {
    const stage = (globalThis as unknown as { __stage?: {
      app: { canvas: HTMLCanvasElement }; camera: { x: number; y: number; scale: number };
    } }).__stage;
    if (!stage) throw new Error("GM canvas missing");
    const rect = stage.app.canvas.getBoundingClientRect();
    return { x: rect.left + (900 - stage.camera.x) * stage.camera.scale,
      y: rect.top + (650 - stage.camera.y) * stage.camera.scale };
  });
  const before = await hostCall<number>(page, "seq");
  await page.mouse.click(point.x, point.y);
  await expect.poll(() => hostCall<number>(page, "seq")).toBeGreaterThan(before);
  await expect(page.locator("#chat-log")).toContainText("Once 1");
  const contents = await page.locator("#chat-log").innerText();
  const visited = [...contents.matchAll(/Visited ([12])\/(t-[a-f0-9]{8})/g)];
  expect(visited).toHaveLength(2);
  expect(visited.map((match) => match[1])).toEqual(["1", "2"]);
  expect(visited[0]?.[2]).not.toBe(visited[1]?.[2]);
  const after = await hostCall<number>(page, "seq");
  await page.mouse.click(point.x, point.y);
  await expect.poll(() => hostCall<number>(page, "seq")).toBeGreaterThan(after);
  const again = await page.locator("#chat-log").innerText();
  expect([...again.matchAll(/Once 1/g)]).toHaveLength(1); // tile count 2 stopped before routing
  expect([...again.matchAll(/Visited [12]\/t-[a-f0-9]{8}/g)]).toHaveLength(4);
});

test("GM authors a persistent tile counter, branches on its next fire, reloads and clears variables separately", async ({ page }) => {
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  await zones.locator("[data-zone-tile-create]").getByLabel("Tile name").fill("Counting tile");
  await zones.locator("[data-zone-create-tile]").click();
  await expect(zones.locator("[data-zone-tile] option").filter({ hasText: "Counting tile" })).toHaveCount(1);
  await zones.locator("[data-zone-name]").fill("Counting trap");
  await zones.getByRole("button", { name: "Remove step 2" }).click(); // default notice is before the branch
  await zones.locator('[data-zone-add="set"]').click();
  const counter = zones.locator("[data-zone-step]").last();
  await counter.getByLabel("Name").fill("visits");
  await counter.getByLabel("Scope").selectOption("tile");
  await counter.getByLabel("Variable operation").selectOption("add");
  await counter.getByLabel("Value", { exact: true }).fill("1");
  await zones.locator('[data-zone-add="filter"]').click();
  const check = zones.locator("[data-zone-step]").last();
  await check.getByLabel("Check").selectOption("variable");
  await check.getByLabel("Variable", { exact: true }).fill("visits");
  await check.getByLabel("Equals", { exact: true }).fill("2");
  await zones.locator('[data-zone-add="chat"]').click();
  const notice = zones.locator("[data-zone-step]").last();
  await notice.getByLabel("Text").fill("Visits {{visits}}");
  await zones.locator("[data-zone-save]").click();
  await expect(zones.locator("li").filter({ hasText: "Counting trap" })).toHaveCount(1);
  await expect(zones.getByRole("alert")).toHaveCount(0);
  await zones.getByLabel("Simulate method").selectOption("manual");
  const before = await hostCall<number>(page, "seq");
  await zones.locator("[data-zone-run]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 1);
  await expect(zones.locator("[data-zone-variables]")).toHaveCount(1);
  await expect(page.locator("#chat-log")).not.toContainText("Visits 1");
  await zones.locator("[data-zone-run]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 2);
  await expect(page.locator("#chat-log")).toContainText("Visits 2");
  await zones.locator("[data-zone-variables] summary").click();
  await expect(zones.locator("[data-zone-variables] li")).toContainText("visits: 2");
  expect(await hostCall<number>(page, "drainOps")).toBe(await hostCall<number>(page, "seq"));
  await page.reload();
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const restored = page.locator("[data-active-zones]");
  await restored.locator("[data-zone-variables] summary").click();
  await expect(restored.locator("[data-zone-variables] li")).toContainText("visits: 2");
  await restored.locator("[data-zone-reset-history]").click();
  await expect(restored.locator("[data-zone-history]")).toHaveCount(0);
  await expect(restored.locator("[data-zone-variables] li")).toContainText("visits: 2");
  await restored.locator("[data-zone-clear-variables]").click();
  await expect(restored.locator("[data-zone-variables]")).toHaveCount(0);
});

test("wizard activates a paused tile graph and invokes it in one undoable host fire", async ({ page }) => {
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  const create = async (name: string, x: number) => {
    const editor = zones.locator("[data-zone-tile-create]");
    await editor.getByLabel("Tile name").fill(name);
    await editor.getByLabel("X", { exact: true }).fill(String(x));
    await editor.locator("[data-zone-create-tile]").click();
    const option = zones.locator("[data-zone-tile] option").filter({ hasText: name });
    await expect(option).toHaveCount(1);
    const id = await option.getAttribute("value");
    if (!id) throw new Error(`tile ${name} missing an ID`);
    return id;
  };
  const parent = await create("Wake switch", 100);
  const child = await create("Sleeping gate", 450);
  await zones.locator("[data-zone-tile]").selectOption(child);
  await zones.locator("[data-zone-name]").fill("Sleeping tile graph");
  await zones.locator(".gates").getByLabel("Paused").check();
  await zones.locator('[data-zone-step="notice"]').getByLabel("Text").fill("Gate awakened {{charge}}");
  await zones.locator("[data-zone-save]").click();
  await expect(zones.locator("li").filter({ hasText: "Sleeping tile graph" })).toHaveCount(1);

  await zones.getByRole("button", { name: "New" }).click();
  await zones.locator("[data-zone-tile]").selectOption(parent);
  await zones.locator("[data-zone-name]").fill("Wake switch graph");
  await zones.getByRole("button", { name: "Remove step 2" }).click();
  await zones.locator('[data-zone-add="setActive"]').click();
  const enable = zones.locator("[data-zone-step]").last();
  await enable.getByLabel("Set tile graph activity").selectOption("activate");
  await enable.getByLabel("Activity tile").selectOption(child);
  await zones.locator('[data-zone-add="set"]').click();
  const assign = zones.locator("[data-zone-step]").last();
  await assign.getByLabel("Name", { exact: true }).fill("charge");
  await assign.getByLabel("Variable scope").selectOption("tile");
  await assign.getByLabel("Variable target").selectOption("id");
  await assign.getByLabel("Variable tile").selectOption(child);
  await assign.getByLabel("Value", { exact: true }).fill("3");
  await zones.locator('[data-zone-add="triggerTile"]').click();
  await zones.getByRole("combobox", { name: "Tile", exact: true }).selectOption(child);
  await zones.locator("[data-zone-save]").click();
  await expect(zones.getByRole("alert")).toHaveCount(0);
  await zones.getByLabel("Simulate method").selectOption("manual");
  const before = await hostCall<number>(page, "seq");
  await zones.locator("[data-zone-run]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 1);
  await expect(page.locator("#chat-log")).toContainText("Gate awakened 3");
  await expect(zones.locator("details[open] li").filter({ hasText: /activate 1 graph/ })).toHaveCount(1);
  await expect(zones.locator("details[open] li").filter({ hasText: /tile variable charge = on 1 graph/ })).toHaveCount(1);
  const savedChild = zones.locator("li").filter({ hasText: "Sleeping tile graph" });
  await expect(savedChild).toContainText("1 run(s)");
  await savedChild.getByRole("button", { name: "Edit" }).click();
  await expect(zones.locator(".gates").getByLabel("Paused")).not.toBeChecked();
  await zones.locator("[data-zone-variables] summary").click();
  await expect(zones.locator("[data-zone-variables] li")).toContainText("charge: 3");
  await page.getByRole("button", { name: /Undo \(Ctrl\+Z\)/ }).click();
  await expect(savedChild).toContainText("0 run(s)");
  await savedChild.getByRole("button", { name: "Edit" }).click(); // refresh the editor's unsaved copy
  await expect(zones.locator(".gates").getByLabel("Paused")).toBeChecked();
  await expect(zones.locator("[data-zone-variables]")).toHaveCount(0);
  await expect.poll(() => hostCall<string[]>(page, "chatLines")).toEqual([]);
  await expect(page.locator("#chat-log")).not.toContainText("Gate awakened");
  await hostCall<number>(page, "drainOps");
  await page.reload();
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const restored = page.locator("[data-active-zones]");
  await restored.locator("li").filter({ hasText: "Sleeping tile graph" })
    .getByRole("button", { name: "Edit" }).click();
  await expect(restored.locator(".gates").getByLabel("Paused")).toBeChecked();
  await expect(page.locator("#chat-log")).not.toContainText("Gate awakened");
});

test("a connected player's canvas click invokes the published tile without receiving a graph ID", async ({ browser }: { browser: Browser }) => {
  test.setTimeout(90_000);
  const hostCtx = await browser.newContext();
  const playerCtx = await browser.newContext();
  try {
    const host = await hostCtx.newPage();
    const player = await playerCtx.newPage();
    await host.goto(entry + "?e2e=1");
    await waitForSurface(host, "app");
    await host.locator("#gm-macros").click();
    await host.locator("[data-macro-zones-tab]").click();
    const zones = host.locator("[data-active-zones]");
    await zones.locator("[data-zone-tile-create] summary").click();
    const tile = zones.locator("[data-zone-tile-create]");
    await tile.getByLabel("Tile name").fill("Public bell");
    await tile.getByLabel("X", { exact: true }).fill("350");
    await tile.getByLabel("Y", { exact: true }).fill("400");
    await tile.getByLabel("Width").fill("200");
    await tile.getByLabel("Height").fill("160");
    await tile.locator("[data-zone-create-tile]").click();
    await expect(zones.locator("[data-zone-tile] option").filter({ hasText: "Public bell" })).toHaveCount(1);
    await zones.locator("[data-zone-name]").fill("Player bell");
    await zones.locator(".methods label").filter({ hasText: "click" }).locator("input").check();
    await zones.getByLabel("Player click (published)").check();
    await zones.locator("[data-zone-save]").click();
    await expect(zones.locator("li").filter({ hasText: "Player bell" })).toHaveCount(1);
    await host.locator('[data-window="macros"] [data-window-close]').click();

    await host.locator("#share").click();
    const fragment = manualFragment(await host.locator("#invite-link").inputValue());
    await player.goto(`${entry}?e2e=1&join=1#${fragment}`);
    await expect.poll(() => player.locator("#offer-out").inputValue(), { timeout: 20_000 }).not.toBe("");
    await host.locator("#peer-code").fill(await player.locator("#offer-out").inputValue());
    await host.locator("#code-apply").click();
    await expect.poll(() => host.locator("#share-out").inputValue(), { timeout: 20_000 }).not.toBe("");
    await player.locator("#answer-input").fill(await host.locator("#share-out").inputValue());
    await player.locator("#answer-apply").click();
    await expect.poll(() => playerCall<boolean>(player, "connected"), { timeout: 30_000 }).toBe(true);
    await waitForSurface(player, "playerCanvas");
    const before = await hostCall<number>(host, "seq");
    await expect.poll(() => playerCall<number>(player, "seq")).toBeGreaterThanOrEqual(before);
    const point = await surfaceCallArg<{ x: number; y: number } | null>(player, "playerCanvas", "screenOf", { x: 450, y: 480 });
    if (!point) throw new Error("player canvas point unavailable");
    await player.mouse.click(point.x, point.y);
    await expect.poll(() => hostCall<number>(host, "seq"), { timeout: 20_000 }).toBeGreaterThan(before);
    await expect(host.locator("#chat-log")).toContainText("click by");
  } finally {
    await playerCtx.close();
    await hostCtx.close();
  }
});

test("wizard authors a real batch barrier and GM tile trigger priority", async ({ page }) => {
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  const tile = zones.locator("[data-zone-tile-create]");
  await tile.getByLabel("Tile name").fill("Batch tile");
  await tile.getByLabel("Trigger sort").fill("7");
  await tile.locator("[data-zone-create-tile]").click();
  await expect(zones.locator("[data-zone-tile] option").filter({ hasText: "Batch tile" })).toHaveCount(1);
  const priority = zones.getByRole("spinbutton", { name: /Selected tile trigger sort/ });
  await expect(priority).toHaveValue("7");
  await priority.fill("11");
  await priority.press("Tab");
  await expect(priority).toHaveValue("11");
  await zones.locator("[data-zone-name]").fill("Batch bell");
  await zones.locator('[data-zone-step="select"]').getByLabel("Current collection").selectOption("tile");
  await zones.locator('[data-zone-add="tags"]').click();
  await zones.locator('[data-zone-add="batchFlush"]').click();
  await zones.locator('[data-zone-add="tags"]').click();
  await zones.locator("[data-zone-step]").last().getByLabel("Edit").selectOption("remove");
  await zones.locator('[data-zone-add="batchFlush"]').click();
  await zones.locator("[data-zone-save]").click();
  await expect(zones.locator("li").filter({ hasText: "Batch bell" })).toHaveCount(1);
  await expect(zones.getByRole("alert")).toHaveCount(0);
  const before = await hostCall<number>(page, "seq");
  await zones.locator("[data-zone-run]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 1); // both batches in one host commit
  await expect(zones.getByRole("status")).toContainText("committed");
  await expect(zones.locator("details[open] li").filter({ hasText: "batch executed" })).toHaveCount(2);
  await expect(zones.locator("details[open] li").filter({ hasText: "1 combined world update(s)" })).toHaveCount(2);
  await expect(priority).toHaveValue("11");
});

test("wizard authors a current-collection edit and atomic Trigger Tile call with origin context", async ({ page }) => {
  test.setTimeout(60_000);
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  const createTile = async (name: string, x: number) => {
    const editor = zones.locator("[data-zone-tile-create]");
    await editor.getByLabel("Tile name").fill(name);
    await editor.getByLabel("X", { exact: true }).fill(String(x));
    await editor.getByLabel("Y", { exact: true }).fill("400");
    await editor.getByLabel("Width").fill("180");
    await editor.getByLabel("Height").fill("160");
    await editor.locator("[data-zone-create-tile]").click();
    const option = zones.locator("[data-zone-tile] option").filter({ hasText: name });
    await expect(option).toHaveCount(1);
    const id = await option.getAttribute("value");
    if (!id) throw new Error(`tile ${name} did not receive a host ID`);
    return id;
  };
  const parentTile = await createTile("Relay parent", 350);
  const childTile = await createTile("Relay child", 650);
  await zones.locator("[data-zone-tile]").selectOption(childTile);
  await zones.locator("[data-zone-name]").fill("Relay child graph");
  await zones.locator(".methods label").filter({ hasText: "enter" }).locator("input").uncheck();
  await zones.locator(".methods label").filter({ hasText: "stop" }).locator("input").uncheck();
  await zones.locator('[data-zone-step="notice"]').getByLabel("Text").fill("Child of {{originMethod}}");
  await zones.locator("[data-zone-save]").click();
  await expect(zones.locator("li").filter({ hasText: "Relay child graph" })).toHaveCount(1);

  await zones.getByRole("button", { name: "New" }).click();
  await zones.locator("[data-zone-tile]").selectOption(parentTile);
  await zones.locator("[data-zone-name]").fill("Relay parent graph");
  await zones.locator(".methods label").filter({ hasText: "click" }).locator("input").check();
  await zones.locator('[data-zone-step="notice"]').getByLabel("Text").fill("Parent {{method}}");
  await zones.locator('[data-zone-add="collection"]').click();
  const collection = zones.locator("[data-zone-step]").last();
  await collection.getByLabel("Change current collection").selectOption("replace");
  await collection.getByLabel("Entities").selectOption("tile");
  await zones.locator('[data-zone-add="filter"]').click();
  const filter = zones.locator("[data-zone-step]").last();
  await filter.getByLabel("At least").fill("1");
  await filter.getByLabel("At most").fill("1");
  await zones.locator('[data-zone-add="triggerTile"]').click();
  const call = zones.locator("[data-zone-step]").last();
  await call.getByLabel("Target tiles").selectOption("id");
  await call.getByRole("combobox", { name: "Tile", exact: true }).selectOption(childTile);
  await call.getByLabel("Pass tokens").selectOption("triggering");
  await zones.locator("[data-zone-save]").click();
  await expect(zones.locator("li").filter({ hasText: "Relay parent graph" })).toHaveCount(1);
  await expect(zones.getByRole("alert")).toHaveCount(0);

  await page.locator('[data-window="macros"] [data-window-close]').click();
  await page.locator('[data-canvas-layer="map"]').click();
  const point = await page.evaluate(() => {
    const stage = (globalThis as unknown as { __stage?: {
      app: { canvas: HTMLCanvasElement }; camera: { x: number; y: number; scale: number };
    } }).__stage;
    if (!stage) throw new Error("GM canvas missing");
    const rect = stage.app.canvas.getBoundingClientRect();
    return { x: rect.left + (440 - stage.camera.x) * stage.camera.scale,
      y: rect.top + (480 - stage.camera.y) * stage.camera.scale };
  });
  const before = await hostCall<number>(page, "seq");
  await page.mouse.click(point.x, point.y);
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 1); // parent AND child in one envelope
  await expect(page.locator("#chat-log")).toContainText("Parent click");
  await expect(page.locator("#chat-log")).toContainText("Child of click");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  await expect(zones.locator("li").filter({ hasText: "Relay parent graph" })).toContainText("1 run(s)");
  await expect(zones.locator("li").filter({ hasText: "Relay child graph" })).toContainText("1 run(s)");
});
