import { expect, test } from "@playwright/test";
import { entry, hostCall, waitForSurface } from "./lib";

test("GM captures a tile and linked graph, previews and places two atomic prefabs, then despawns one", async ({ page }) => {
  await page.goto(entry + "?e2e=1");
  await waitForSurface(page, "app");
  await page.locator("#gm-macros").click();
  await page.locator("[data-macro-zones-tab]").click();
  const zones = page.locator("[data-active-zones]");
  await zones.locator("[data-zone-tile-create] summary").click();
  const tile = zones.locator("[data-zone-tile-create]");
  await tile.getByLabel("Tile name").fill("Prefab bell");
  await tile.getByLabel("X", { exact: true }).fill("350");
  await tile.getByLabel("Y", { exact: true }).fill("400");
  await tile.getByLabel("Width").fill("160");
  await tile.getByLabel("Height").fill("160");
  await tile.locator("[data-zone-create-tile]").click();
  await expect(zones.locator("[data-zone-tile] option").filter({ hasText: "Prefab bell" })).toHaveCount(1);
  await zones.locator("[data-zone-name]").fill("Bell graph");
  await zones.locator(".methods label").filter({ hasText: "click" }).locator("input").check();
  await zones.locator("[data-zone-save]").click();
  await expect(zones.locator("li").filter({ hasText: "Bell graph" })).toHaveCount(1);

  await page.locator("[data-macro-prefabs-tab]").click();
  const panel = page.locator("[data-prefab-panel]");
  await panel.locator("[data-prefab-name]").fill("Two bells");
  await panel.locator("[data-prefab-parts]").getByText("Prefab bell").click();
  await expect(panel.locator("[data-prefab-root]")).not.toHaveValue("");
  await panel.locator("[data-prefab-save]").click();
  await expect(panel.getByRole("status")).toContainText("1 graphs");
  await expect(panel.locator("[data-prefab-list] option").filter({ hasText: "Two bells" })).toHaveCount(1);
  await panel.getByLabel("X", { exact: true }).fill("500");
  await panel.getByLabel("Y", { exact: true }).fill("450");
  await panel.locator("[data-prefab-preview]").click();
  await expect(panel.getByRole("status")).toContainText("2 atomic creates");
  const before = await hostCall<number>(page, "seq");
  await panel.locator("[data-prefab-place]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 1);
  await expect(panel.locator("[data-prefab-instances] summary")).toContainText("1");
  await panel.getByLabel("X", { exact: true }).fill("720");
  await panel.locator("[data-prefab-place]").click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 2);
  await expect(panel.locator("[data-prefab-instances] summary")).toContainText("2");
  await panel.locator("[data-prefab-instances] summary").click();
  page.once("dialog", (dialog) => void dialog.accept());
  await panel.locator("[data-prefab-instances] button").first().click();
  await expect.poll(() => hostCall<number>(page, "seq")).toBe(before + 3);
  await expect(panel.locator("[data-prefab-instances] summary")).toContainText("1");
});
